### ISSUE TITLE
unrecognized OS: darwin

### ISSUE THREAD

**Issue by ahmetb** [rewanthtammana/kubectl-whisper-secret#1]
```
ccsecret generic my-secret --from-literal key1 --from-literal key2
Enter value for key1 :
Enter value for key2 :
Unrecognized OS: darwin
Please create an issue here, https://github.com/rewanth1997/kubectl-ccsecret/issues
```

**Comment by nikolay** [comment]
@ahmetb It also doesn't install view `krew`.

**Comment by rewanth1997** [comment]
@nikolay I can install it via krew on ubuntu. I haven't tested this on macos or darwin, hence I dropped the support. I will release an update soon with darwin support.

![image](https://user-images.githubusercontent.com/22347290/110840859-a8a95980-82be-11eb-9fdd-98e6781ec4b4.png)
